export function createRunMiscModuleResult() {
  return {
    message: "ok",
    text: "generic result",
    table: {
      columns: [
        { key: "field", label: "Field" },
        { key: "value", label: "Value" },
      ],
      rows: [{ field: "keyword", value: "cmd.exe" }],
    },
  };
}

export function createMiscModulesFixture() {
  return [
    {
      id: "http-login-analysis",
      kind: "builtin",
      title: "HTTP 登录行为分析",
      summary: "http auth summary",
      tags: ["HTTP", "Login"],
      apiPrefix: "/api/tools/http-login-analysis",
      docsPath: "docs/misc-module-interface.md",
      requiresCapture: true,
      protocolDomain: "HTTP / Auth",
      supportsExport: true,
      cancellable: true,
      dependsOn: ["capture", "http"],
    },
    {
      id: "payload-webshell-decoder",
      kind: "builtin",
      title: "Payload / WebShell 解码工作台",
      summary: "payload decoder summary",
      tags: ["Payload", "WebShell", "Decode", "Base64"],
      apiPrefix: "/api/streams",
      docsPath: "docs/misc-module-interface.md",
      requiresCapture: false,
      protocolDomain: "Payload / WebShell",
      supportsExport: true,
      cancellable: true,
      dependsOn: ["payload", "decode"],
    },
    {
      id: "mysql-session-analysis",
      kind: "builtin",
      title: "MySQL 会话重建",
      summary: "mysql summary",
      tags: ["MySQL", "DB"],
      apiPrefix: "/api/tools/mysql-analysis",
      docsPath: "docs/misc-module-interface.md",
      requiresCapture: true,
      protocolDomain: "MySQL / Database",
      supportsExport: true,
      cancellable: true,
      dependsOn: ["capture", "mysql"],
    },
    {
      id: "smtp-session-analysis",
      kind: "builtin",
      title: "SMTP 会话重建",
      summary: "smtp summary",
      tags: ["SMTP", "Mail"],
      apiPrefix: "/api/tools/smtp-analysis",
      docsPath: "docs/misc-module-interface.md",
      requiresCapture: true,
      protocolDomain: "SMTP / Mail",
      supportsExport: true,
      cancellable: true,
      dependsOn: ["capture", "smtp"],
    },
    {
      id: "shiro-rememberme-analysis",
      kind: "builtin",
      title: "Shiro rememberMe 分析",
      summary: "shiro summary",
      tags: ["Shiro", "rememberMe"],
      apiPrefix: "/api/tools/shiro-rememberme",
      docsPath: "docs/misc-module-interface.md",
      requiresCapture: true,
      protocolDomain: "HTTP / Shiro",
      supportsExport: true,
      cancellable: true,
      dependsOn: ["capture", "http"],
    },
    {
      id: "winrm-decrypt",
      kind: "builtin",
      title: "WinRM 解密辅助",
      summary: "winrm summary",
      tags: ["WinRM"],
      apiPrefix: "/api/tools/winrm-decrypt",
      docsPath: "docs/misc-module-interface.md",
      requiresCapture: true,
      protocolDomain: "NTLM / WinRM",
      supportsExport: true,
      cancellable: true,
      dependsOn: ["capture", "http", "ntlm"],
    },
    {
      id: "ntlm-session-materials",
      kind: "builtin",
      title: "NTLM 会话材料中心",
      summary: "ntlm summary",
      tags: ["NTLM", "HTTP", "WinRM", "SMB3"],
      apiPrefix: "/api/tools/ntlm-sessions",
      docsPath: "docs/misc-module-interface.md",
      requiresCapture: true,
      protocolDomain: "NTLM",
      supportsExport: true,
      cancellable: false,
      dependsOn: ["capture", "ntlm"],
    },
    {
      id: "smb3-session-key",
      kind: "builtin",
      title: "SMB3 Random Session Key",
      summary: "smb summary",
      tags: ["SMB3"],
      apiPrefix: "/api/tools/smb3",
      docsPath: "docs/misc-module-interface.md",
      requiresCapture: true,
      protocolDomain: "SMB3 / NTLM",
      supportsExport: false,
      cancellable: false,
      dependsOn: ["capture", "ntlm"],
    },
  ];
}
