export const LAYER_TITLES: Record<string, string> = {
  frame: "Frame",
  eth: "Ethernet II",
  sll: "Linux cooked capture",
  sll2: "Linux cooked capture v2",
  ip: "Internet Protocol Version 4",
  ipv4: "Internet Protocol Version 4",
  ipv6: "Internet Protocol Version 6",
  tcp: "Transmission Control Protocol",
  udp: "User Datagram Protocol",
  http: "Hypertext Transfer Protocol",
  tls: "Transport Layer Security",
  ssl: "Secure Sockets Layer",
  dns: "Domain Name System",
  arp: "Address Resolution Protocol",
  icmp: "Internet Control Message Protocol",
  icmpv6: "Internet Control Message Protocol v6",
  igmp: "Internet Group Management Protocol",
  smb: "Server Message Block",
  smb2: "Server Message Block v2",
  quic: "Quick UDP Internet Connections",
  ssh: "Secure Shell",
  ftp: "File Transfer Protocol",
  data: "Data",
};

export const TOKEN_LABELS: Record<string, string> = {
  addr: "Address",
  ack: "ACK",
  ascii: "ASCII",
  cap: "Captured",
  checksum: "Checksum",
  crc: "CRC",
  df: "DF",
  dns: "DNS",
  dst: "Dst",
  ecn: "ECN",
  eth: "Ethernet",
  frame: "Frame",
  hdr: "Header",
  host: "Host",
  http: "HTTP",
  icmp: "ICMP",
  icmpv6: "ICMPv6",
  id: "ID",
  igmp: "IGMP",
  ip: "IP",
  ipv6: "IPv6",
  len: "Length",
  lg: "LG",
  mac: "MAC",
  mf: "MF",
  oui: "OUI",
  port: "Port",
  proto: "Protocol",
  raw: "Raw",
  rb: "RB",
  seq: "Seq",
  smb: "SMB",
  smb2: "SMB2",
  src: "Src",
  ssl: "SSL",
  stream: "Stream",
  tcp: "TCP",
  tls: "TLS",
  ttl: "TTL",
  udp: "UDP",
  uri: "URI",
  utc: "UTC",
  ver: "Version",
};

export const HIDDEN_LAYER_KEYS = new Set([
  "_ws_lua__ws_lua_fake",
]);

export const DEFAULT_PLUGIN_LOGS = [
  "[INFO] 插件引擎启动完成",
  "[INFO] 规则加载: 131 条",
  "[DEBUG] 等待数据流输入",
];
