import type { MiscModuleManifest } from "../core/types";

export const frontendOnlyModules: MiscModuleManifest[] = [
  {
    id: "base64-codec",
    title: "Base64 / Hex / URL 编解码",
    summary: "双向编解码工具，支持 Base64、Hex、URL 编码转换",
    kind: "builtin",
    tags: ["payload", "decode", "encode"],
    apiPrefix: "",
    protocolDomain: "通用",
    requiresCapture: false,
    supportsExport: false,
    cancellable: false,
  },
  {
    id: "timestamp-converter",
    title: "时间戳转换",
    summary: "Unix 时间戳与日期字符串双向转换",
    kind: "builtin",
    tags: ["timestamp", "date", "convert"],
    apiPrefix: "",
    protocolDomain: "通用",
    requiresCapture: false,
    supportsExport: false,
    cancellable: false,
  },
  {
    id: "hash-calculator",
    title: "哈希计算器",
    summary: "计算文本的 CRC32、SHA-1、SHA-256 哈希值",
    kind: "builtin",
    tags: ["hash", "sha", "crc", "encode"],
    apiPrefix: "",
    protocolDomain: "通用",
    requiresCapture: false,
    supportsExport: false,
    cancellable: false,
  },
  {
    id: "udp-tunnel-detection",
    title: "UDP 隧道识别",
    summary: "检测 DNS 隧道、通用 UDP 隧道等隐蔽通道行为",
    kind: "builtin",
    tags: ["protocol", "tunnel", "dns"],
    apiPrefix: "",
    protocolDomain: "UDP/DNS",
    requiresCapture: true,
    supportsExport: false,
    cancellable: true,
  },
  {
    id: "bruteforce-detection",
    title: "端口/目录爆破识别",
    summary: "检测端口扫描（SYN scan）和 HTTP 目录爆破行为",
    kind: "builtin",
    tags: ["protocol", "scan", "bruteforce"],
    apiPrefix: "",
    protocolDomain: "TCP/HTTP",
    requiresCapture: true,
    supportsExport: false,
    cancellable: true,
  },
];
