// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHypothesisEvidence(arg1, arg2) {
  return window['go']['main']['DesktopApp']['AddHypothesisEvidence'](arg1, arg2);
}

export function AddVehicleDBC(arg1) {
  return window['go']['main']['DesktopApp']['AddVehicleDBC'](arg1);
}

export function AllowTSharkDir(arg1) {
  return window['go']['main']['DesktopApp']['AllowTSharkDir'](arg1);
}

export function AllowToolDir(arg1, arg2) {
  return window['go']['main']['DesktopApp']['AllowToolDir'](arg1, arg2);
}

export function BackendStatus() {
  return window['go']['main']['DesktopApp']['BackendStatus']();
}

export function CancelMediaBatchTranscription() {
  return window['go']['main']['DesktopApp']['CancelMediaBatchTranscription']();
}

export function CheckAppUpdate() {
  return window['go']['main']['DesktopApp']['CheckAppUpdate']();
}

export function CheckRuleUpdates() {
  return window['go']['main']['DesktopApp']['CheckRuleUpdates']();
}

export function CloseCapture() {
  return window['go']['main']['DesktopApp']['CloseCapture']();
}

export function CreateHypothesis(arg1) {
  return window['go']['main']['DesktopApp']['CreateHypothesis'](arg1);
}

export function CreatePlaybook(arg1) {
  return window['go']['main']['DesktopApp']['CreatePlaybook'](arg1);
}

export function CreateSavedSearch(arg1) {
  return window['go']['main']['DesktopApp']['CreateSavedSearch'](arg1);
}

export function DecodeStreamPayload(arg1) {
  return window['go']['main']['DesktopApp']['DecodeStreamPayload'](arg1);
}

export function DecryptC2Traffic(arg1) {
  return window['go']['main']['DesktopApp']['DecryptC2Traffic'](arg1);
}

export function DeleteHypothesis(arg1) {
  return window['go']['main']['DesktopApp']['DeleteHypothesis'](arg1);
}

export function DeleteMiscModulePackage(arg1) {
  return window['go']['main']['DesktopApp']['DeleteMiscModulePackage'](arg1);
}

export function DeletePlaybook(arg1) {
  return window['go']['main']['DesktopApp']['DeletePlaybook'](arg1);
}

export function DeleteSavedSearch(arg1) {
  return window['go']['main']['DesktopApp']['DeleteSavedSearch'](arg1);
}

export function DownloadMediaArtifact(arg1) {
  return window['go']['main']['DesktopApp']['DownloadMediaArtifact'](arg1);
}

export function DownloadObjectsZip(arg1) {
  return window['go']['main']['DesktopApp']['DownloadObjectsZip'](arg1);
}

export function DownloadRulePack(arg1, arg2, arg3) {
  return window['go']['main']['DesktopApp']['DownloadRulePack'](arg1, arg2, arg3);
}

export function ExecuteSavedSearch(arg1) {
  return window['go']['main']['DesktopApp']['ExecuteSavedSearch'](arg1);
}

export function ExportMediaBatchTranscription(arg1) {
  return window['go']['main']['DesktopApp']['ExportMediaBatchTranscription'](arg1);
}

export function ExportWinRMDecryptResult(arg1) {
  return window['go']['main']['DesktopApp']['ExportWinRMDecryptResult'](arg1);
}

export function GenerateSMB3RandomSessionKey(arg1) {
  return window['go']['main']['DesktopApp']['GenerateSMB3RandomSessionKey'](arg1);
}

export function GetAPTAnalysis() {
  return window['go']['main']['DesktopApp']['GetAPTAnalysis']();
}

export function GetBackendAuthToken() {
  return window['go']['main']['DesktopApp']['GetBackendAuthToken']();
}

export function GetBruteforceAnalysis() {
  return window['go']['main']['DesktopApp']['GetBruteforceAnalysis']();
}

export function GetC2SampleAnalysis(arg1) {
  return window['go']['main']['DesktopApp']['GetC2SampleAnalysis'](arg1);
}

export function GetCaptureStatus() {
  return window['go']['main']['DesktopApp']['GetCaptureStatus']();
}

export function GetDesktopWebviewSmokeConfig() {
  return window['go']['main']['DesktopApp']['GetDesktopWebviewSmokeConfig']();
}

export function GetEvidence() {
  return window['go']['main']['DesktopApp']['GetEvidence']();
}

export function GetEvidenceWithFilter(arg1) {
  return window['go']['main']['DesktopApp']['GetEvidenceWithFilter'](arg1);
}

export function GetGlobalTrafficStats() {
  return window['go']['main']['DesktopApp']['GetGlobalTrafficStats']();
}

export function GetHTTPLoginAnalysis() {
  return window['go']['main']['DesktopApp']['GetHTTPLoginAnalysis']();
}

export function GetHttpStream(arg1) {
  return window['go']['main']['DesktopApp']['GetHttpStream'](arg1);
}

export function GetHuntingRuntimeConfig() {
  return window['go']['main']['DesktopApp']['GetHuntingRuntimeConfig']();
}

export function GetHypothesis(arg1) {
  return window['go']['main']['DesktopApp']['GetHypothesis'](arg1);
}

export function GetIndustrialAnalysis(arg1) {
  return window['go']['main']['DesktopApp']['GetIndustrialAnalysis'](arg1);
}

export function GetMCPStatus() {
  return window['go']['main']['DesktopApp']['GetMCPStatus']();
}

export function GetMediaAnalysis(arg1) {
  return window['go']['main']['DesktopApp']['GetMediaAnalysis'](arg1);
}

export function GetMediaBatchTranscriptionStatus() {
  return window['go']['main']['DesktopApp']['GetMediaBatchTranscriptionStatus']();
}

export function GetMediaPlaybackBlob(arg1) {
  return window['go']['main']['DesktopApp']['GetMediaPlaybackBlob'](arg1);
}

export function GetMySQLAnalysis() {
  return window['go']['main']['DesktopApp']['GetMySQLAnalysis']();
}

export function GetPacket(arg1) {
  return window['go']['main']['DesktopApp']['GetPacket'](arg1);
}

export function GetPacketLayers(arg1) {
  return window['go']['main']['DesktopApp']['GetPacketLayers'](arg1);
}

export function GetPacketRawHex(arg1) {
  return window['go']['main']['DesktopApp']['GetPacketRawHex'](arg1);
}

export function GetPlaybook(arg1) {
  return window['go']['main']['DesktopApp']['GetPlaybook'](arg1);
}

export function GetPlaybookLastRun(arg1) {
  return window['go']['main']['DesktopApp']['GetPlaybookLastRun'](arg1);
}

export function GetRawStream(arg1, arg2) {
  return window['go']['main']['DesktopApp']['GetRawStream'](arg1, arg2);
}

export function GetRawStreamPage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['DesktopApp']['GetRawStreamPage'](arg1, arg2, arg3, arg4);
}

export function GetRuleConflicts() {
  return window['go']['main']['DesktopApp']['GetRuleConflicts']();
}

export function GetRuleStatus() {
  return window['go']['main']['DesktopApp']['GetRuleStatus']();
}

export function GetSMTPAnalysis() {
  return window['go']['main']['DesktopApp']['GetSMTPAnalysis']();
}

export function GetSavedSearch(arg1) {
  return window['go']['main']['DesktopApp']['GetSavedSearch'](arg1);
}

export function GetShiroRememberMeAnalysis(arg1) {
  return window['go']['main']['DesktopApp']['GetShiroRememberMeAnalysis'](arg1);
}

export function GetTLSConfig() {
  return window['go']['main']['DesktopApp']['GetTLSConfig']();
}

export function GetToolRuntimeSnapshot() {
  return window['go']['main']['DesktopApp']['GetToolRuntimeSnapshot']();
}

export function GetToolRuntimeSnapshotFast() {
  return window['go']['main']['DesktopApp']['GetToolRuntimeSnapshotFast']();
}

export function GetToolRuntimeSnapshotFull() {
  return window['go']['main']['DesktopApp']['GetToolRuntimeSnapshotFull']();
}

export function GetUDPTunnelAnalysis() {
  return window['go']['main']['DesktopApp']['GetUDPTunnelAnalysis']();
}

export function GetUSBAnalysis(arg1, arg2, arg3) {
  return window['go']['main']['DesktopApp']['GetUSBAnalysis'](arg1, arg2, arg3);
}

export function GetVehicleAnalysis(arg1) {
  return window['go']['main']['DesktopApp']['GetVehicleAnalysis'](arg1);
}

export function GetWinRMDecryptResultText(arg1) {
  return window['go']['main']['DesktopApp']['GetWinRMDecryptResultText'](arg1);
}

export function ImportMiscModulePackageFromPath(arg1) {
  return window['go']['main']['DesktopApp']['ImportMiscModulePackageFromPath'](arg1);
}

export function InspectStreamPayload(arg1) {
  return window['go']['main']['DesktopApp']['InspectStreamPayload'](arg1);
}

export function InstallAppUpdate() {
  return window['go']['main']['DesktopApp']['InstallAppUpdate']();
}

export function IsBackendReady() {
  return window['go']['main']['DesktopApp']['IsBackendReady']();
}

export function ListHypotheses(arg1) {
  return window['go']['main']['DesktopApp']['ListHypotheses'](arg1);
}

export function ListMiscModules() {
  return window['go']['main']['DesktopApp']['ListMiscModules']();
}

export function ListNTLMSessionMaterials() {
  return window['go']['main']['DesktopApp']['ListNTLMSessionMaterials']();
}

export function ListObjects() {
  return window['go']['main']['DesktopApp']['ListObjects']();
}

export function ListPacketsPage(arg1, arg2, arg3) {
  return window['go']['main']['DesktopApp']['ListPacketsPage'](arg1, arg2, arg3);
}

export function ListPlaybooks() {
  return window['go']['main']['DesktopApp']['ListPlaybooks']();
}

export function ListSMB3SessionCandidates() {
  return window['go']['main']['DesktopApp']['ListSMB3SessionCandidates']();
}

export function ListSavedSearches() {
  return window['go']['main']['DesktopApp']['ListSavedSearches']();
}

export function ListStreamIDs(arg1) {
  return window['go']['main']['DesktopApp']['ListStreamIDs'](arg1);
}

export function ListStreamPayloadSources(arg1) {
  return window['go']['main']['DesktopApp']['ListStreamPayloadSources'](arg1);
}

export function ListTSharkAllowedDirs() {
  return window['go']['main']['DesktopApp']['ListTSharkAllowedDirs']();
}

export function ListThreatHits(arg1) {
  return window['go']['main']['DesktopApp']['ListThreatHits'](arg1);
}

export function ListToolAllowedDirs(arg1) {
  return window['go']['main']['DesktopApp']['ListToolAllowedDirs'](arg1);
}

export function ListVehicleDBCProfiles() {
  return window['go']['main']['DesktopApp']['ListVehicleDBCProfiles']();
}

export function LocatePacketPage(arg1, arg2, arg3) {
  return window['go']['main']['DesktopApp']['LocatePacketPage'](arg1, arg2, arg3);
}

export function OpenCaptureDialog() {
  return window['go']['main']['DesktopApp']['OpenCaptureDialog']();
}

export function OpenDBCDialog() {
  return window['go']['main']['DesktopApp']['OpenDBCDialog']();
}

export function PingBackendDataPlane() {
  return window['go']['main']['DesktopApp']['PingBackendDataPlane']();
}

export function PrepareCaptureReplacement() {
  return window['go']['main']['DesktopApp']['PrepareCaptureReplacement']();
}

export function RemoveTSharkAllowedDir(arg1) {
  return window['go']['main']['DesktopApp']['RemoveTSharkAllowedDir'](arg1);
}

export function RemoveToolAllowedDir(arg1, arg2) {
  return window['go']['main']['DesktopApp']['RemoveToolAllowedDir'](arg1, arg2);
}

export function RemoveVehicleDBC(arg1) {
  return window['go']['main']['DesktopApp']['RemoveVehicleDBC'](arg1);
}

export function RunMiscModulePackage(arg1, arg2) {
  return window['go']['main']['DesktopApp']['RunMiscModulePackage'](arg1, arg2);
}

export function RunPlaybook(arg1) {
  return window['go']['main']['DesktopApp']['RunPlaybook'](arg1);
}

export function RunWinRMDecrypt(arg1) {
  return window['go']['main']['DesktopApp']['RunWinRMDecrypt'](arg1);
}

export function SelectMiscModulePackage() {
  return window['go']['main']['DesktopApp']['SelectMiscModulePackage']();
}

export function SetTSharkPath(arg1) {
  return window['go']['main']['DesktopApp']['SetTSharkPath'](arg1);
}

export function StartCapture(arg1, arg2) {
  return window['go']['main']['DesktopApp']['StartCapture'](arg1, arg2);
}

export function StartMediaBatchTranscription(arg1) {
  return window['go']['main']['DesktopApp']['StartMediaBatchTranscription'](arg1);
}

export function StopCapture() {
  return window['go']['main']['DesktopApp']['StopCapture']();
}

export function ToggleRulePack(arg1, arg2) {
  return window['go']['main']['DesktopApp']['ToggleRulePack'](arg1, arg2);
}

export function TranscribeMediaArtifact(arg1, arg2) {
  return window['go']['main']['DesktopApp']['TranscribeMediaArtifact'](arg1, arg2);
}

export function UpdateHuntingRuntimeConfig(arg1) {
  return window['go']['main']['DesktopApp']['UpdateHuntingRuntimeConfig'](arg1);
}

export function UpdateHypothesis(arg1, arg2) {
  return window['go']['main']['DesktopApp']['UpdateHypothesis'](arg1, arg2);
}

export function UpdateHypothesisStatus(arg1, arg2, arg3) {
  return window['go']['main']['DesktopApp']['UpdateHypothesisStatus'](arg1, arg2, arg3);
}

export function UpdateMCPConfig(arg1) {
  return window['go']['main']['DesktopApp']['UpdateMCPConfig'](arg1);
}

export function UpdatePlaybook(arg1, arg2) {
  return window['go']['main']['DesktopApp']['UpdatePlaybook'](arg1, arg2);
}

export function UpdateRuleConfig(arg1) {
  return window['go']['main']['DesktopApp']['UpdateRuleConfig'](arg1);
}

export function UpdateSavedSearch(arg1, arg2) {
  return window['go']['main']['DesktopApp']['UpdateSavedSearch'](arg1, arg2);
}

export function UpdateStreamPayloads(arg1, arg2, arg3) {
  return window['go']['main']['DesktopApp']['UpdateStreamPayloads'](arg1, arg2, arg3);
}

export function UpdateTLSConfig(arg1) {
  return window['go']['main']['DesktopApp']['UpdateTLSConfig'](arg1);
}

export function UpdateToolRuntimeConfig(arg1) {
  return window['go']['main']['DesktopApp']['UpdateToolRuntimeConfig'](arg1);
}

export function UpdateToolRuntimeConfigFast(arg1) {
  return window['go']['main']['DesktopApp']['UpdateToolRuntimeConfigFast'](arg1);
}

export function UpdateToolRuntimeConfigFull(arg1) {
  return window['go']['main']['DesktopApp']['UpdateToolRuntimeConfigFull'](arg1);
}

export function ValidateRules(arg1) {
  return window['go']['main']['DesktopApp']['ValidateRules'](arg1);
}

export function WriteDesktopWebviewSmokeResult(arg1) {
  return window['go']['main']['DesktopApp']['WriteDesktopWebviewSmokeResult'](arg1);
}
