// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackendStatus():Promise<string>;
export function CheckAppUpdate():Promise<any>;
export function CloseCapture():Promise<void>;
export function GetBackendAuthToken():Promise<string>;
export function GetCaptureStatus():Promise<any>;
export function ListPacketsPage(cursor:number, limit:number, filter:string):Promise<any>;
export function GetTLSConfig():Promise<any>;
export function GetToolRuntimeSnapshot():Promise<any>;
export function GetToolRuntimeSnapshotFast():Promise<any>;
export function GetToolRuntimeSnapshotFull():Promise<any>;
export function InstallAppUpdate():Promise<void>;
export function IsBackendReady():Promise<boolean>;
export function OpenCaptureDialog():Promise<any>;
export function OpenDBCDialog():Promise<any>;
export function PrepareCaptureReplacement():Promise<void>;
export function SetTSharkPath(path:string):Promise<any>;
export function StartCapture(filePath:string, filter:string):Promise<void>;
export function StopCapture():Promise<void>;
export function UpdateTLSConfig(cfg:any):Promise<void>;
export function UpdateToolRuntimeConfig(cfg:any):Promise<any>;
export function UpdateToolRuntimeConfigFast(cfg:any):Promise<any>;
export function UpdateToolRuntimeConfigFull(cfg:any):Promise<any>;
