// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddHypothesisEvidence(arg1:string,arg2:Record<string, any>):Promise<any>;

export function AddVehicleDBC(arg1:string):Promise<any>;

export function AllowTSharkDir(arg1:string):Promise<Record<string, any>>;

export function AllowToolDir(arg1:string,arg2:string):Promise<Record<string, any>>;

export function BackendStatus():Promise<string>;

export function CancelMediaBatchTranscription():Promise<any>;

export function CheckAppUpdate():Promise<main.AppUpdateStatus>;

export function CheckRuleUpdates():Promise<any>;

export function CloseCapture():Promise<void>;

export function CreateHypothesis(arg1:Record<string, any>):Promise<any>;

export function CreatePlaybook(arg1:Record<string, any>):Promise<any>;

export function CreateSavedSearch(arg1:Record<string, any>):Promise<any>;

export function DecodeStreamPayload(arg1:main.desktopStreamDecodeRequest):Promise<any>;

export function DecryptC2Traffic(arg1:main.desktopC2DecryptRequest):Promise<any>;

export function DeleteHypothesis(arg1:string):Promise<any>;

export function DeleteMiscModulePackage(arg1:string):Promise<any>;

export function DeletePlaybook(arg1:string):Promise<any>;

export function DeleteSavedSearch(arg1:string):Promise<any>;

export function DownloadMediaArtifact(arg1:string):Promise<main.desktopBackendBlob>;

export function DownloadObjectsZip(arg1:Array<number>):Promise<main.desktopBackendBlob>;

export function DownloadRulePack(arg1:string,arg2:string,arg3:string):Promise<any>;

export function ExecuteSavedSearch(arg1:string):Promise<any>;

export function ExportMediaBatchTranscription(arg1:string):Promise<main.desktopBackendBlob>;

export function ExportWinRMDecryptResult(arg1:string):Promise<main.desktopBackendBlob>;

export function GenerateSMB3RandomSessionKey(arg1:main.desktopSMB3RandomSessionKeyRequest):Promise<any>;

export function GetAPTAnalysis():Promise<any>;

export function GetBackendAuthToken():Promise<string>;

export function GetBruteforceAnalysis():Promise<any>;

export function GetC2SampleAnalysis(arg1:boolean):Promise<any>;

export function GetCaptureStatus():Promise<Record<string, any>>;

export function GetDesktopWebviewSmokeConfig():Promise<main.desktopWebviewSmokeConfig>;

export function GetEvidence():Promise<any>;

export function GetEvidenceWithFilter(arg1:Array<string>):Promise<any>;

export function GetGlobalTrafficStats():Promise<any>;

export function GetHTTPLoginAnalysis():Promise<any>;

export function GetHttpStream(arg1:number):Promise<any>;

export function GetHuntingRuntimeConfig():Promise<any>;

export function GetHypothesis(arg1:string):Promise<any>;

export function GetIndustrialAnalysis(arg1:boolean):Promise<any>;

export function GetMCPStatus():Promise<Record<string, any>>;

export function GetMediaAnalysis(arg1:boolean):Promise<any>;

export function GetMediaBatchTranscriptionStatus():Promise<any>;

export function GetMediaPlaybackBlob(arg1:string):Promise<main.desktopBackendBlob>;

export function GetMySQLAnalysis():Promise<any>;

export function GetPacket(arg1:number):Promise<Record<string, any>>;

export function GetPacketLayers(arg1:number):Promise<any>;

export function GetPacketRawHex(arg1:number):Promise<any>;

export function GetPlaybook(arg1:string):Promise<any>;

export function GetPlaybookLastRun(arg1:string):Promise<any>;

export function GetRawStream(arg1:string,arg2:number):Promise<any>;

export function GetRawStreamPage(arg1:string,arg2:number,arg3:number,arg4:number):Promise<any>;

export function GetRuleConflicts():Promise<any>;

export function GetRuleStatus():Promise<any>;

export function GetSMTPAnalysis():Promise<any>;

export function GetSavedSearch(arg1:string):Promise<any>;

export function GetShiroRememberMeAnalysis(arg1:Array<string>):Promise<any>;

export function GetTLSConfig():Promise<main.desktopTLSConfig>;

export function GetToolRuntimeSnapshot():Promise<Record<string, any>>;

export function GetToolRuntimeSnapshotFast():Promise<Record<string, any>>;

export function GetToolRuntimeSnapshotFull():Promise<Record<string, any>>;

export function GetUDPTunnelAnalysis():Promise<any>;

export function GetUSBAnalysis(arg1:string,arg2:number,arg3:boolean):Promise<any>;

export function GetVehicleAnalysis(arg1:boolean):Promise<any>;

export function GetWinRMDecryptResultText(arg1:string):Promise<string>;

export function ImportMiscModulePackageFromPath(arg1:string):Promise<any>;

export function InspectStreamPayload(arg1:string):Promise<any>;

export function InstallAppUpdate():Promise<void>;

export function IsBackendReady():Promise<boolean>;

export function ListHypotheses(arg1:string):Promise<any>;

export function ListMiscModules():Promise<any>;

export function ListNTLMSessionMaterials():Promise<any>;

export function ListObjects():Promise<any>;

export function ListPacketsPage(arg1:number,arg2:number,arg3:string):Promise<Record<string, any>>;

export function ListPlaybooks():Promise<any>;

export function ListSMB3SessionCandidates():Promise<any>;

export function ListSavedSearches():Promise<any>;

export function ListStreamIDs(arg1:string):Promise<any>;

export function ListStreamPayloadSources(arg1:number):Promise<any>;

export function ListTSharkAllowedDirs():Promise<main.desktopToolAllowedDirs>;

export function ListThreatHits(arg1:Array<string>):Promise<any>;

export function ListToolAllowedDirs(arg1:string):Promise<main.desktopToolAllowedDirs>;

export function ListVehicleDBCProfiles():Promise<any>;

export function LocatePacketPage(arg1:number,arg2:number,arg3:string):Promise<Record<string, any>>;

export function OpenCaptureDialog():Promise<main.openCaptureDialogResult>;

export function OpenDBCDialog():Promise<main.openCaptureDialogResult>;

export function PingBackendDataPlane():Promise<main.desktopBackendProbe>;

export function PrepareCaptureReplacement():Promise<void>;

export function RemoveTSharkAllowedDir(arg1:string):Promise<Record<string, any>>;

export function RemoveToolAllowedDir(arg1:string,arg2:string):Promise<Record<string, any>>;

export function RemoveVehicleDBC(arg1:string):Promise<any>;

export function RunMiscModulePackage(arg1:string,arg2:Record<string, string>):Promise<any>;

export function RunPlaybook(arg1:string):Promise<any>;

export function RunWinRMDecrypt(arg1:main.desktopWinRMDecryptRequest):Promise<any>;

export function SelectMiscModulePackage():Promise<main.openCaptureDialogResult>;

export function SetTSharkPath(arg1:string):Promise<Record<string, any>>;

export function StartCapture(arg1:string,arg2:string):Promise<void>;

export function StartMediaBatchTranscription(arg1:boolean):Promise<any>;

export function StopCapture():Promise<void>;

export function ToggleRulePack(arg1:string,arg2:boolean):Promise<any>;

export function TranscribeMediaArtifact(arg1:string,arg2:boolean):Promise<any>;

export function UpdateHuntingRuntimeConfig(arg1:main.desktopHuntingRuntimeConfig):Promise<any>;

export function UpdateHypothesis(arg1:string,arg2:Record<string, any>):Promise<any>;

export function UpdateHypothesisStatus(arg1:string,arg2:string,arg3:string):Promise<any>;

export function UpdateMCPConfig(arg1:main.desktopMCPConfig):Promise<Record<string, any>>;

export function UpdatePlaybook(arg1:string,arg2:Record<string, any>):Promise<any>;

export function UpdateRuleConfig(arg1:Record<string, any>):Promise<any>;

export function UpdateSavedSearch(arg1:string,arg2:Record<string, any>):Promise<any>;

export function UpdateStreamPayloads(arg1:string,arg2:number,arg3:Array<main.desktopStreamPayloadPatch>):Promise<any>;

export function UpdateTLSConfig(arg1:main.desktopTLSConfig):Promise<void>;

export function UpdateToolRuntimeConfig(arg1:main.desktopToolRuntimeConfig):Promise<Record<string, any>>;

export function UpdateToolRuntimeConfigFast(arg1:main.desktopToolRuntimeConfig):Promise<Record<string, any>>;

export function UpdateToolRuntimeConfigFull(arg1:main.desktopToolRuntimeConfig):Promise<Record<string, any>>;

export function ValidateRules(arg1:string):Promise<any>;

export function WriteDesktopWebviewSmokeResult(arg1:Record<string, any>):Promise<void>;
